### ISSUE TITLE
AJAX Cart 

### ISSUE THREAD

**Issue by jabberdog** [jabberdog/SURYA-MAGE-1.9-001#16]
Add AJAX cart functionality to the store.

**Comment by jabberdog** [comment]
AJAX Cart Pro installed: https://ecommerce.aheadworks.com/magento-extensions/ajax-cart-pro.html

Documentation: http://confluence.aheadworks.com/display/EUDOC/Ajax+Cart+Pro

**Comment by Florinnn** [comment]
Hi Ben,

Next week in between the other stuff on MH site we need to style a bit the ajax cart on Surya ( by that I mean to add an image for it exactly like we do for Wholesale, arrange the 2 buttons to make it look better for customers). So I will ask Ray to do a nice image next week and you will use that to style it a bit. As said you can take as reference the example of Ajax cart we have on Wholesale.

Thanks,
Florin

**Comment by jabberdog** [comment]
Hello everyone. Has Ray created the graphic yet? If so, and this task has not been completed still - are you able to attach it by dragging and dropping into this task?

**Comment by Florinnn** [comment]
Hi Liam,

We don't have the image from Ray yet as he was in a rush the whole week with different stuff (adverts, mailshots etc). Leave it with me, I will add it here as soon as I have it from Ray. Once I have the image I will assign Ben to work on this ticket.

Thanks,
Florin

**Comment by Florinnn** [comment]
Ben,

Attached you can find the image for the Surya ajax cart.
Please style the ajax cart on Surya to look similar with the one we have on Wholesale when adding a product to cart. In the above have the AJAX Cart Pro documentation from Liam too.
![surya_cart](https://user-images.githubusercontent.com/29812956/31075696-be2cb560-a76e-11e7-8b67-e220ce0ad744.png)

Florin

**Comment by developerWLED** [comment]
Hi @Florinnn 

I have acknowledged your comment florin, however we are having issues with my local repository and gits not being synced, moving forward i am going to get in touch with the hosting company so that they can send me a copy of the site, and then i will be able to complete the necessary steps in order to complete this task.

Thanks
Ben

**Comment by developerWLED** [comment]
HI @Florinnn,
I have added the image to the AJAX cart and styled accordingly, please let me know if there is anything else that needs to be done in this regard.

**Comment by Florinnn** [comment]
Hi,

1. You need to fix the mobile view because it looks very bad.  Also I see the product page is not anymore responsive (see the horizontal scrolling bar). See below a screenshot of it:
![mobile_view_surya_cart](https://user-images.githubusercontent.com/29812956/31131571-6fd10652-a852-11e7-8022-d81c30eba55d.jpg)

2. Into the title that stais on top of the ajax cart please add this bit "has been added to cart" so that the customers gets the idea of it (same like we do on Wholesale as said). So the title on top area of the ajax cart poping up will sound like this: [Product Title] has been added to cart.

Florin

**Comment by Florinnn** [comment]
3. On **Portrait** tablet view it seems **all** products are hidden by default on home page & all categories across the store most likely due to some style changes made recently. See below:
![portrait_tablet-view](https://user-images.githubusercontent.com/29812956/31132077-c39a4b9e-a853-11e7-9f1c-0de579c35044.jpg)

**Comment by developerWLED** [comment]
added mobile styles to ajax cart

**Comment by Florinnn** [comment]
For issue regarding the mobile view please check if the image with the cart really fits in the ajax cart window as just looked on mobile and I see just half of the cart on right side of pop up window. See image below:
![mobile_view-surya_cart](https://user-images.githubusercontent.com/29812956/31136550-80ecc076-a860-11e7-9566-0912914297f3.jpg)

**Comment by developerWLED** [comment]
![22281264_10156663167799951_1283273978_o](https://user-images.githubusercontent.com/29500145/31166220-e675603a-a8e5-11e7-82f9-41c7dd521f7a.jpg)
![screenshot_20171004-091509](https://user-images.githubusercontent.com/29500145/31166236-efc9c48c-a8e5-11e7-940c-9d2bee85bf23.png)

Hi @Florinnn These are screenshots from both an android device and iphone 6 device, and i can't replicate the problem as all seems fine here.

**Comment by Florinnn** [comment]
Hi,

When checking please try and check usually how it looks like on smaller devices (if looks okay on smaller devices then we know for sure it looks fine on bigger devices too and not the oposite). The above printscreen is from a **4s** Iphone. I've just done a test with a **5s** Iphone too and here is how it looks like (same issue). See below:
![iphone_5s](https://user-images.githubusercontent.com/29812956/31167167-0356aabc-a8e9-11e7-8f68-970fb5d92147.jpg)

On a side note, the validation message when pressing add to cart without choosing the option overlaps with the ADD TO CART option (that one I know for sure was expanding between the drop down selection and Add to cart). See below:
![validation_message](https://user-images.githubusercontent.com/29812956/31167179-0e7f0f7e-a8e9-11e7-9bd9-1d0ed2d6c207.png)

Florin

**Comment by developerWLED** [comment]
Hi @Florinnn 
Both issues above have been corrected.

**Comment by Florinnn** [comment]
Hi,

Checked the 2 issues from the above and all seems working fine.
However, just spotted that **on all devices** when adding few products to cart, then move to cart page, then delete one product from the cart, it shows up a pop up window like the one you've implemented, with just a button on top saying Continue Shopping and some white space around it which is useless. Can you ensure that one doesn't pops up at this step as doesn't make sense since we invite customers to press Continue Shopping on it just to stay into the same Cart page where the user is supposed to stay anyway. See printscreen below:
![cart_pop-up_window](https://user-images.githubusercontent.com/29812956/31172697-8426c006-a8fc-11e7-9143-4007656692b3.jpg)

Florin

**Comment by developerWLED** [comment]
HI @Florinnn if you can check now this problem is solved.
![screen shot 2017-10-06 at 10 50 30](https://user-images.githubusercontent.com/29500145/31272825-30fc04de-aa84-11e7-8034-f14a6f4354de.png)

**Comment by Florinnn** [comment]
Sorted, all good
